### ISSUE TITLE
Aceitar apenas números de 1 a 9 nas posições de jogo

### ISSUE THREAD

**Issue by navigatoralia** [navigatoralia/tictactoe#21]
Ou o programa vai crashar

**Comment by vialrogo** [comment]
Precisa mais detalhes. Tenta que os issues sejam assim:

# Validar a entrada do usuário
Quando o usuário ingressa alguma coisa que não seja uma posição válida, o programa crashei porque tenta converter a entrada a número. Deve se mostrar uma mensagem ao usuário comunicando o erro e pedir de novo o número.

Assim fica bem melhor

**Comment by vialrogo** [comment]
Vamos juntar com #17 e fazer duma vez as duas

**Comment by navigatoralia** [comment]
blz, vou abrir a branch

**Comment by vialrogo** [comment]
mudança de planos, vamos deixar #17 queto, tenho que trocar muita coisa

**Comment by vialrogo** [comment]
Este issue tinha várias coisas, fechei que ele aceite só números. Falta o outro. Fecho este e abro outros
